// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSahpPacglu86_x_bEj82B710c_AX0n5E',
    appId: '1:288736113067:web:e6b230ddaf28c1689ae2ee',
    messagingSenderId: '288736113067',
    projectId: 'notification-service-545b7',
    authDomain: 'notification-service-545b7.firebaseapp.com',
    storageBucket: 'notification-service-545b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9fw_jq0gNEiPGL5VCGtB-PSWUYZRIws',
    appId: '1:288736113067:android:dea5284c79d1cc219ae2ee',
    messagingSenderId: '288736113067',
    projectId: 'notification-service-545b7',
    storageBucket: 'notification-service-545b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRC8j9F4mNOBJbDthdSIKDsBstIFpMOgY',
    appId: '1:288736113067:ios:347d2ebb9a7c0e3a9ae2ee',
    messagingSenderId: '288736113067',
    projectId: 'notification-service-545b7',
    storageBucket: 'notification-service-545b7.firebasestorage.app',
    iosBundleId: 'com.example.bathroomVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRC8j9F4mNOBJbDthdSIKDsBstIFpMOgY',
    appId: '1:288736113067:ios:347d2ebb9a7c0e3a9ae2ee',
    messagingSenderId: '288736113067',
    projectId: 'notification-service-545b7',
    storageBucket: 'notification-service-545b7.firebasestorage.app',
    iosBundleId: 'com.example.bathroomVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSahpPacglu86_x_bEj82B710c_AX0n5E',
    appId: '1:288736113067:web:07aec8cabf4821ab9ae2ee',
    messagingSenderId: '288736113067',
    projectId: 'notification-service-545b7',
    authDomain: 'notification-service-545b7.firebaseapp.com',
    storageBucket: 'notification-service-545b7.firebasestorage.app',
  );

}